/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_camera_free: (a: number, b: number) => void;
export const __wbg_get_camera_aspect_ratio: (a: number) => number;
export const __wbg_get_camera_image_width: (a: number) => number;
export const __wbg_get_camera_max_depth: (a: number) => number;
export const __wbg_get_camera_samples_per_pixel: (a: number) => number;
export const __wbg_get_camera_vfov: (a: number) => number;
export const __wbg_hittablelist_free: (a: number, b: number) => void;
export const __wbg_set_camera_aspect_ratio: (a: number, b: number) => void;
export const __wbg_set_camera_image_width: (a: number, b: number) => void;
export const __wbg_set_camera_max_depth: (a: number, b: number) => void;
export const __wbg_set_camera_samples_per_pixel: (a: number, b: number) => void;
export const __wbg_set_camera_vfov: (a: number, b: number) => void;
export const camera_new: () => number;
export const camera_render: (a: number, b: number) => [number, number];
export const camera_set_lookat: (a: number, b: number, c: number, d: number) => void;
export const camera_set_lookfrom: (a: number, b: number, c: number, d: number) => void;
export const camera_set_vup: (a: number, b: number, c: number, d: number) => void;
export const hittablelist_add_glass_sphere: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const hittablelist_add_hollow_glass_sphere: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const hittablelist_add_matte_sphere: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const hittablelist_add_metal_sphere: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const hittablelist_clear: (a: number) => void;
export const hittablelist_new: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
